---
- import_role:
    name: common
    tasks_from: check-mandatory.yml
  vars:
    common_mandatory_vars: "{{ zookeeper_mandatory_vars }}"
- name: install confluent platform
  import_role:
    name: common

- name: ensure config and data directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ zookeeper_base_dir }}"
    - "{{ zookeeper_config_dir }}"
    - "{{ zookeeper_data_dir }}"
- name: configure zookeeper properties
  template:
    src: zookeeper.properties.j2
    dest: "{{ zookeeper_config_dir }}/zookeeper.properties"
  notify:
    - zookeeper_restart_zookeeper
- name: configure zookeeper id
  copy:
    content: "{{ myid }}"
    dest: "{{ zookeeper_data_dir }}/myid"
  notify:
    - zookeeper_restart_zookeeper
- name: configure zookeeper log4j properties
  copy:
    src: zookeeper-log4j.properties
    dest: "{{ zookeeper_config_dir }}/zookeeper-log4j.properties"
  notify:
    - zookeeper_restart_zookeeper
- name: configure zookeeper JAAS
  template:
    src: zookeeper-jaas.conf.j2
    dest: "{{ zookeeper_config_dir }}/zookeeper-jaas.conf"
    mode: u=r,g=,o=
  notify:
    - zookeeper_restart_zookeeper
- name: configure start script
  template:
    src: start.j2
    dest: "{{ zookeeper_base_dir }}/start"
    mode: u+x
  notify:
    - zookeeper_restart_zookeeper
- name: configure systemd unit file
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  become: true
  notify:
    - zookeeper_reload_systemd_config
    - zookeeper_restart_zookeeper

- name: ensure zookeeper service
  systemd:
    name: zookeeper
    enabled: true
    state: started
  become: true

