---
kafka_base_dir: "{{ ansible_env.HOME }}"
kafka_config_dir: "{{ kafka_base_dir }}/config"
kafka_log_dir: "{{ kafka_base_dir }}/logs"
kafka_data_dir: "{{ kafka_base_dir }}/data/kafka"
kafka_truststore: "{{ kafka_base_dir }}/keystores/kafka.server.truststore.jks"
kafka_keystore: "{{ kafka_base_dir }}/keystores/kafka.server.keystore.jks"
kafka_bin: "{{ common_confluent_dir }}/bin"
kafka_zookeeper_service_target: zookeeper.target

kafka_mandatory_vars:
  - kafka_user
  - kafka_truststore_pass
  - kafka_keystore_pass
  - kafka_key_pass
  - kafka_kafkabroker_pass
  - kafka_client_pass
  - kafka_zookeeper_kafka_pass

