---
kafka_base_dir: "{{ ansible_env.HOME }}/kafka"
kafka_config_dir: "{{ kafka_base_dir }}/config"
kafka_log_dir: "{{ kafka_base_dir }}/logs"
kafka_data_dir: "{{ kafka_base_dir }}/data"
kafka_truststore: "{{ ansible_env.HOME }}/keystores/kafka.server.truststore.jks"
kafka_keystore: "{{ ansible_env.HOME }}/keystores/kafka.server.keystore.jks"
kafka_bin: "{{ common_confluent_dir }}/bin"
kafka_zookeeper_client_port: 2181
kafka_zookeeper_connect_urls: "{{ groups['zookeeper'] | map('regex_replace', '^(.*)$', '\\1:' ~ kafka_zookeeper_client_port) | join(',') }}"
kafka_zookeeper_service_target: zookeeper.target

kafka_mandatory_vars:
  - kafka_user
  - kafka_truststore_pass
  - kafka_keystore_pass
  - kafka_key_pass
  - kafka_kafkabroker_pass
  - kafka_client_pass
  - kafka_zookeeper_kafka_pass
