---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../.lint/.yamllint
platforms:
  - &zookeeper-instance
    name: zookeeper-1
    image: minimum2scp/systemd-stretch
    command: /sbin/init
    privileged: True
    network_mode: bridge
    networks:
      - name: zoo
  - <<: *zookeeper-instance
    name: zookeeper-2
  - <<: *zookeeper-instance
    name: zookeeper-3
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
    host_vars:
      zookeeper-1:
        myid: 1
      zookeeper-2:
        myid: 2
      zookeeper-3:
        myid: 3
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      config: ../../.lint/.flake8

