---
- name: Converge
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
  roles:
    - role: zookeeper
      vars:
        zookeeper_super_pass: admin-pass
        zookeeper_kafka_pass: kafka-pass

