---
version: 2.1
jobs:
  test-role:
    parameters:
      role-name:
        type: string
    docker:
      - image: quay.io/ansible/molecule:2.22rc3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install test dependencies
          command: apk add --update --no-cache bash openssl openjdk8-jre
      - run:
          name: test << parameters.role-name >> role
          command: |
            cd ansible/roles/<< parameters.role-name >>
            molecule test
workflows:
  test:
    jobs:
      - test-role:
          name: test-role-zookeeper
          role-name: zookeeper
      - test-role:
          name: test-role-kafka
          role-name: kafka

