---
- import_role:
    name: common
    tasks_from: check-mandatory.yml
  vars:
    common_mandatory_vars: "{{ kafka_mandatory_vars }}"
- name: install confluent platform
  import_role:
    name: common

- name: ensure config and data directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ kafka_base_dir }}"
    - "{{ kafka_config_dir }}"
    - "{{ kafka_data_dir }}"
- name: configure kafka properties
  template:
    src: server.properties.j2
    dest: "{{ kafka_config_dir }}/server.properties"
  notify:
    - kafka_restart_kafka
- name: configure kafka log4j properties
  copy:
    src: kafka-log4j.properties
    dest: "{{ kafka_config_dir }}/kafka-log4j.properties"
  notify:
    - kafka_restart_kafka
- name: configure kafka JAAS
  template:
    src: kafka-server-jaas.conf.j2
    dest: "{{ kafka_config_dir }}/kafka-server-jaas.conf"
    mode: u=r,g=,o=
  notify:
    - kafka_restart_kafka
- name: configure start script
  template:
    src: start.j2
    dest: "{{ kafka_base_dir }}/start"
    mode: u+x
  notify:
    - kafka_restart_kafka
- name: configure systemd unit file
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
  become: true
  notify:
    - kafka_reload_systemd_config
    - kafka_restart_kafka

- name: ensure kafka service
  systemd:
    name: kafka
    enabled: true
    state: started
  become: true

