---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../.lint/.yamllint
platforms:
  - &kafka-instance
    name: kafka-1
    groups:
      - kafka
      - zookeeper
    image: minimum2scp/systemd-stretch
    command: /sbin/init
    privileged: true
    network_mode: bridge
    networks:
      - name: kafka
  - <<: *kafka-instance
    name: kafka-2
  - <<: *kafka-instance
    name: kafka-3
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: ansible
    host_vars:
      kafka-1:
        broker_id: 1
        myid: 1
        cert_dname: 'CN=kafka-1'
      kafka-2:
        broker_id: 2
        myid: 2
        cert_dname: 'CN=kafka-2'
      kafka-3:
        broker_id: 3
        myid: 3
        cert_dname: 'CN=kafka-3'
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      config: ../../.lint/.flake8
