---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ../../.lint/.yamllint
platforms:
  - name: kafka-1
    groups:
      - kafka
    image: debian:9
    network_mode: bridge
    networks:
      - name: kafka
  - name: kafka-2
    groups:
      - kafka
    image: debian:9
    network_mode: bridge
    networks:
      - name: kafka
  - name: kafka-3
    groups:
      - kafka
    image: debian:9
    network_mode: bridge
    networks:
      - name: kafka
provisioner:
  name: ansible
  inventory:
    host_vars:
      kafka-1:
        broker_id: 1
        myid: 1
        cert_dname: 'CN=kafka-1'
      kafka-2:
        broker_id: 2
        myid: 2
        cert_dname: 'CN=kafka-2'
      kafka-3:
        broker_id: 3
        myid: 3
        cert_dname: 'CN=kafka-3'
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      config: ../../.lint/.flake8

