---
- hosts: zookeeper
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
  tasks:
    - import_role:
        name: zookeeper

- hosts: kafka
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
  tasks:
    - import_role:
        name: kafka
